//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateNewProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateNewProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///for /f &quot;tokens=4&quot; %%A in (&apos;mode^|findstr &quot;COM[0-9]:&quot;&apos;) do set DEVICE=%%A
        ///set AVAILABLECOMPORT=%DEVICE:~0,-1%
        ///
        ///SET LANG=C
        ///SET mypath=%~dp0
        ///SET robotloader_cmd_exe=&quot;%mypath:~0,-1%\..\..\robotloader_cmd.exe&quot;
        ///SET robotloader_path=&quot;%mypath:~0,-1%\..\..\&quot;
        ///SET project_path=%mypath:~0,-1%\
        ///
        ///for /f &quot;delims=\&quot; %%a in (&quot;%project_path%&quot;) do SET project_name=%%~nxa
        ///SET hexfile=&quot;%project_path%%project_name%.hex&quot;
        ///
        ///if defined AVAILABLECOMPORT if &quot;%AVAILABLECOMPORT%&quot;==&quot;~0,-&quot; GOTO :NODEVICES
        ///
        ///cd /D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompileLinkAndUpload {
            get {
                return ResourceManager.GetString("CompileLinkAndUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;ItemGroup&gt;
        ///    &lt;Filter Include=&quot;util&quot;&gt;
        ///      &lt;UniqueIdentifier&gt;{76f63abe-dacf-423a-85f6-56b679a2a892}&lt;/UniqueIdentifier&gt;
        ///    &lt;/Filter&gt;
        ///    &lt;Filter Include=&quot;source&quot;&gt;
        ///      &lt;UniqueIdentifier&gt;{fca16c96-6b2d-4420-8213-b4384f5c0954}&lt;/UniqueIdentifier&gt;
        ///    &lt;/Filter&gt;
        ///  &lt;/ItemGroup&gt;
        ///  &lt;ItemGroup&gt;
        ///    &lt;None Include=&quot;makefile&quot;&gt;
        ///      &lt;Filter&gt;util&lt;/Filter&gt;
        ///    &lt;/None&gt;
        ///    &lt;No [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void setup(void);
        ///void loop(void);.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Hey Emacs, this is a -*- makefile -*-
        ///###############################################################################
        ///# RP6 MAKEFILE FOR WinAVR
        ///# Based on WinAVR Sample makefile written by Eric B. Weddington,
        ///# Jörg Wunsch, et al.
        ///#
        ///#
        ///# YOU NEED TO EDIT SOME SMALL THINGS IN THIS FILE IF YOU WANT TO USE
        ///# IT FOR YOUR OWN PROJECTS!
        ///# THESE LINES ARE ALL AT THE TOP OF THIS FILE AND MARKED VERY CLEARLY !
        ///# BETTER DO NOT EDIT ANYTHING ELSE!
        ///#
        ///# To compile everything you can simply type &quot;make all&quot; o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string makefile {
            get {
                return ResourceManager.GetString("makefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project DefaultTargets=&quot;Build&quot; ToolsVersion=&quot;12.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;ItemGroup Label=&quot;ProjectConfigurations&quot;&gt;
        ///    &lt;ProjectConfiguration Include=&quot;Debug|Win32&quot;&gt;
        ///      &lt;Configuration&gt;Debug&lt;/Configuration&gt;
        ///      &lt;Platform&gt;Win32&lt;/Platform&gt;
        ///    &lt;/ProjectConfiguration&gt;
        ///  &lt;/ItemGroup&gt;
        ///  &lt;ItemGroup&gt;
        ///    &lt;None Include=&quot;CompileLinkAndUpload.bat&quot; /&gt;
        ///    &lt;None Include=&quot;makefile&quot; /&gt;
        ///  &lt;/ItemGroup&gt;
        ///  &lt;ItemGroup&gt;
        ///    &lt;ClInclu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 12.00
        ///VisualStudioVersion = 12.0.31101.0
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}&quot;) = &quot;&lt;PROJECTNAME&gt;&quot;, &quot;&lt;PROJECTNAME&gt;.vcxproj&quot;, &quot;{37A42495-D54F-4BA1-9C69-788A3AFFD401}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		Debug|Win32 = Debug|Win32
        ///	EndGlobalSection
        ///	GlobalSection(ProjectConfigurationPlatforms) = postSolution
        ///		{37A42495-D54F-4BA1-9C69-788A3AFFD401}.Deb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &quot;RP6ControlLib.h&quot;
        ///#include &quot;&lt;PROJECTNAME&gt;.h&quot;
        ///
        ///int main(void)
        ///{
        ///	setup();
        ///	while(true) 
        ///	{
        ///		loop();
        ///	}
        ///	return 0;
        ///}
        ///
        ///void setup(void)
        ///{
        ///	initRP6Control();
        ///}
        ///
        ///void loop(void)
        ///{
        ///
        ///}.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
    }
}
